staging-settings:
  user-workflow:
    workflow-name: "zkpass-risk-orchestrator"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.staging.json"
    secrets-path: "../secrets.yaml"
